name: "Release"
on:
  push:
    tags:
      - 'v*'

jobs:
  sign:
    environment: build
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g npm
      - run: npm install

      - name: Build
        run: npm run build

      - name: Get the Source Tag
        id: get_source_tag
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - uses: mad9000/actions-find-and-replace-string@2
        id: remove_v
        with:
          source: ${{ steps.get_source_tag.outputs.SOURCE_TAG }}
          find: 'v'
          replace: ''

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: dist/prod

      - name: "web-ext sign"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: unlisted
          apiKey: ${{ secrets.FIREFOX_API_KEY }}
          apiSecret: ${{ secrets.FIREFOX_API_SECRET }}
          timeout: 900000

      - name: "echo filename"
        run: echo ${{ steps.web-ext-sign.outputs.target }}

      - name: "Rename addon file"
        run: mv ${{ steps.web-ext-sign.outputs.target }} web-ext-artifacts/point_network-${{ steps.remove_v.outputs.value }}-an+fx.xpi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_source_tag.outputs.SOURCE_TAG }}
          release_name: Release ${{ steps.get_source_tag.outputs.SOURCE_TAG }}
          draft: true
          prerelease: false

      - name: Upload xpi file
        id: upload_xpi
        uses: pointnetwork/upload-release-asset@v2.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: web-ext-artifacts/point_network-${{ steps.remove_v.outputs.value }}-an+fx.xpi
          asset_name: point_network-${{ steps.remove_v.outputs.value }}-an+fx.xpi
          asset_content_type: application/octet-stream

      - name: Upload manifest
        id: upload_manifest
        uses: pointnetwork/upload-release-asset@v2.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/prod/manifest.json
          asset_name: manifest.json
          asset_content_type: text/plain

      - name: Upload compiled sdk
        id: upload_sdk
        uses: pointnetwork/upload-release-asset@v2.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/prod/pointsdk/index.js
          asset_name: pointsdk-${{ steps.get_source_tag.outputs.SOURCE_TAG }}.js
          asset_content_type: text/javascript

      - name: Generate sha256 file
        uses: DamianReeves/write-file-action@master
        with:
          path: ./sha256
          contents: |
            ${{ steps.upload_xpi.outputs.asset_name }}: ${{ steps.upload_xpi.outputs.asset_hash }}
            ${{ steps.upload_manifest.outputs.asset_name }}: ${{ steps.upload_manifest.outputs.asset_hash }}
            ${{ steps.upload_sdk.outputs.asset_name }}: ${{ steps.upload_sdk.outputs.asset_hash }}

      - name: Upload sha256 file
        uses: pointnetwork/upload-release-asset@v2.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sha256
          asset_name: sha256-${{ steps.get_source_tag.outputs.SOURCE_TAG }}.txt
          asset_content_type: text/plain
